name: Update README Progress

on:
  push:
    branches:
      - main  # Runs on every commit to main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib

      - name: Run Update Script
        run: |
          cd scripts  # Navigate to the correct directory
          python update_readme.py

      - name: Commit and Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md progress_chart.png
          git commit -m 'Updated README with latest progress' || echo "No changes to commit"
          git push https://x-access-token:${GH_PAT}@github.com/heavenstay/leetcode-progress.git HEAD:main